# docker-compose.local.yml

services:
  web:
    image: softvence/django_template:${IMAGE_TAG:-latest}
    container_name: dt_web
    command: >
      gunicorn my_django.wsgi:application
      --bind 0.0.0.0:8000
      --workers 2
      --threads 2
      --timeout 60
      --reload
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "1"
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    image: softvence/django_template:${IMAGE_TAG:-latest}
    container_name: dt_celery_worker
    working_dir: /app
    command: celery -A my_django.celery worker -l info
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "0"
    depends_on:
      - db
      - redis

  celery_beat:
    image: softvence/django_template:${IMAGE_TAG:-latest}
    container_name: dt_celery_beat
    working_dir: /app
    command: celery -A my_django.celery beat -l info
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "0"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: dt_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: dt_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: