# docker-compose.local.yml
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dt_web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "1"
    volumes:
      - .:/app:delegated
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
    networks:
      - dt_network

  celery_worker:
    container_name: dt_celery_worker
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python -m celery -A my_django.celery worker -l info
    working_dir: /app
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "0"
      PYTHONPATH: /app
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - dt_network

  celery_beat:
    container_name: dt_celery_beat
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python -m celery -A my_django.celery beat -l info
    working_dir: /app
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "0"
      PYTHONPATH: /app
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - dt_network

  db:
    image: postgres:15-alpine
    container_name: dt_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dt_network

  redis:
    image: redis:7-alpine
    container_name: dt_redis
    ports:
      - "6379:6379"
    networks:
      - dt_network

networks:
  dt_network:
    driver: bridge

volumes:
  postgres_data:
